truncate table PUPPY_DB.PUPPY_DATA.DAILY_WEIGHT;
truncate table PUPPY_DB.PUPPY_DATA.HOURLY_ACTIVITY;

-- load data into tables
COPY INTO PUPPY_DB.PUPPY_DATA.DAILY_WEIGHT
FROM @raw_data
FILES = ('daily_weight.csv')
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=FALSE,
    FIELD_OPTIONALLY_ENCLOSED_BY=NONE,
    REPLACE_INVALID_CHARACTERS=TRUE,
    DATE_FORMAT='DD/MM/YYYY',
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO
    EMPTY_FIELD_AS_NULL = FALSE
    error_on_column_count_mismatch=false
)
ON_ERROR=ABORT_STATEMENT
FORCE = TRUE ;




COPY INTO PUPPY_DB.PUPPY_DATA.HOURLY_ACTIVITY
FROM @raw_data
FILES = ('hourly_activity.csv')
FILE_FORMAT = (
    TYPE=CSV,
    SKIP_HEADER=1,
    FIELD_DELIMITER=',',
    TRIM_SPACE=FALSE,
    FIELD_OPTIONALLY_ENCLOSED_BY=NONE,
    REPLACE_INVALID_CHARACTERS=TRUE,
    DATE_FORMAT=AUTO,
    TIME_FORMAT=AUTO,
    TIMESTAMP_FORMAT=AUTO
    EMPTY_FIELD_AS_NULL = TRUE
    error_on_column_count_mismatch=false
)
ON_ERROR=ABORT_STATEMENT
FORCE = TRUE ;